sservices:
  - type: web
    name: alurb-ai
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python keep_alive.py & python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
    autoDeploy: true
    healthCheckPath: /health
    plan: free
